### ISSUE TITLE
Optimize muxer selection using noise

### ISSUE THREAD

**Issue by flcl42** [NethermindEth/dotnet-libp2p#18]
Noise can help to establish faster connection by providing information about preferred muxer [during the handshake](https://github.com/libp2p/specs/tree/master/noise#the-libp2p-handshake-payload).

Let's optimize the negotiation by pre-selecting a muxer.

See usage of `IPeerContext.SpecificProtocolRequest`.

**Comment by rose2221** [comment]
hey Alexey, i'd like to work on this issue!
