### ISSUE TITLE
Refactor MultiAddr

### ISSUE THREAD

**Issue by flcl42** [NethermindEth/dotnet-libp2p#20]
`MultiAddr` implementation is limited and not optimal, it asks for improvements. 

Fresh ideas are welcome. Existing ones(that are optional):
- `MultiAddr` requires a lot of allocations, the reason is that it contains address tokens. Let's parse it on demand instead. 
- The class also relies on `Multiaddr` enum and when enum's string representation is needed we use limited ugly switch for that, let's create a generator for the code of Multiaddr-to-string operation.
- Move to a separate module
- Check https://github.com/multiformats/cs-multiaddress ?

**Comment by JuanuMusic** [comment]
Would it be acceptable to fork https://github.com/multiformats/cs-multiaddress and start from there?

**Comment by flcl42** [comment]
@JuanuMusic yep, seems like a viable approach.

**Comment by JuanuMusic** [comment]
Hope you like my PR!

**Comment by JuanuMusic** [comment]
Should we close this one?
